services:
  ui:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./ui/:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
