name: namazo
services:
  ui:
    image: "node:alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=0
    volumes:
      - ./ui/:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
  api:
    image: python:alpine
    build: ./api
    volumes:
      - ./api/:/usr/src/app
    expose:
      - "3001"
    ports:
      - "8001:3001"
    command: "python src/server.py"
    environment:
      - DEBUG=true
    env_file:
      - path: "./.env"
        required: true
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - api
      - ui