import type { Metadata } from "next";
import "@/util/globals.css";
import { Providers } from "./providers";
import Header from "@/components/header/Header";
import Ribbon from "@/components/ribbon/Ribbon";

export const metadata: Metadata = {
  title: "Namazo. Spend more. Frown less.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div className="font-comfortaa">
            <Header />
            <Ribbon />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
