name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create env file
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
  
    - name: Run docker compose
      uses: hoverkraft-tech/compose-action@v2.2.0
      with:
        compose-file: "./docker-compose.yaml"
        up-flags: "--build --detach"

    - name: Wait for UI service to be ready
      run: |
        while [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3000)" != "200" ]; do echo "Waiting for UI service..."; sleep 5; done

    - name: Build static files
      run: |
        docker compose exec ui npm run build

    - name: Start static file server
      run: |
        docker compose up --detach static-server

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
